In [18]:
%load_ext autoreload
%autoreload 2

import importlib
import Data.cargar_datos as data
import fases.fase_1_depuración_inicial.depuracion_columnas as dc
import fases.fase_1_depuración_inicial.excluir_folios as exfol
import fases.fase_1_depuración_inicial.formatear_columnas as formcol
import fases.fase_2_separación_de_grupos.grupo_a as grupo_a
import fases.fase_2_separación_de_grupos.grupo_b as grupo_b
import fases.fase_3_integración.unificar_folios as unificar_folios
import trazabilidad.dataframe as dtframe

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [19]:
importlib.reload(data)
importlib.reload(dc)
importlib.reload(dtframe)
importlib.reload(exfol)

<module 'fases.fase_1_depuración_inicial.excluir_folios' from 'c:\\ARCHIVOS PC\\ARCHIVOS PC\\TRABAJOS UNIVERSIDAD\\PRACTICAS\\EPIDEMIOLOGIA\\Pipeline_Susana_Lopez\\fases\\fase_1_depuración_inicial\\excluir_folios.py'>

# Cargar Datos

In [20]:
ruta = "data/Base_Morbilidad_Enero_2025_75_Columnas.xlsb"
df = data.cargar_database(ruta, sheet_name="Hoja1")
df.head(1)

Leyendo cache...

,OID,HCNTIPHIS,HCCODIGO,HCNOMBRE,NUM_FOLIO,FECHA_FOLIO,MES_VERIFICADO_X_FECHA_FOLIO,AÑO_VERIFICADO_X_FECHA_FOLIO,GENPACIEN,TIPO_IDENTIFICACION,...,OID_DIAPAC,HCNFOLIO,GENDIAGNO,TIP_DX,OID_GENDIAGNO,DIAGNOSTICO,DIAG_NOMBRE,DIAGNO_COMPLETO,GENOCUPACION,OCUPACION_PACIENTE
0,15749626,137,HC067W,HISTORIA CLINICA DE INGRESO A HOSPITALIZACION,13,2025-01-01 00:00:21,enero,2025,573842,Cédula de ciudadanía,...,20775421,15749626,3199,SECUNDARIO,3199,I209,"ANGINA DE PECHO, NO ESPECIFICADA","I209 ANGINA DE PECHO, NO ESPECIFICADA",5,TERCERA EDAD

In [21]:
log = dtframe.LogTrazabilidad()

# Fase 1

## Depuración columnas

In [22]:
df_limpio, log= dc.depurar_columnas(df,log)

In [23]:
filas, columnas = df_limpio.shape
print(f"\nEl DataFrame depurado tiene {filas} filas y {columnas} columnas.")

El DataFrame depurado tiene 198132 filas y 17 columnas.

In [24]:
for i, col in enumerate(df_limpio.columns):
    print(f'  [{i + 1:02d}] {col:<40}')

  [01] CODIGO_FOLIO
  [02] GENERO
  [03] REGIMEN
  [04] TIPO_PACIENTE
  [05] MUNICIPIO
  [06] ZONA
  [07] FECHA_INGRESO
  [08] MES
  [09] AÑO
  [10] EDAD
  [11] NIVEL_SOCIOECONOMICO
  [12] ETNIA
  [13] CODIGO_INGRESO
  [14] TIPO_DIAGNOSTICO
  [15] CIE10
  [16] NOMBRE_DIAGNOSTICO
  [17] OCUPACION_PACIENTE

In [25]:
print(log.obtener().head(20))

                     timestamp ingreso                         campo  \
0   2026-04-21 13:47:45.002081     N/A                           OID
1   2026-04-21 13:47:45.005938     N/A                     HCNTIPHIS
2   2026-04-21 13:47:45.007844     N/A                      HCNOMBRE
3   2026-04-21 13:47:45.009167     N/A                     NUM_FOLIO
4   2026-04-21 13:47:45.010337     N/A                   FECHA_FOLIO
5   2026-04-21 13:47:45.011530     N/A  MES_VERIFICADO_X_FECHA_FOLIO
6   2026-04-21 13:47:45.012672     N/A  AÑO_VERIFICADO_X_FECHA_FOLIO
7   2026-04-21 13:47:45.013818     N/A                     GENPACIEN
8   2026-04-21 13:47:45.014952     N/A           TIPO_IDENTIFICACION
9   2026-04-21 13:47:45.016088     N/A             HC_IDENTIFICACION
10  2026-04-21 13:47:45.017199     N/A               NOMBRE_PACIENTE
11  2026-04-21 13:47:45.018315     N/A                 GRADO_ESTUDIO
12  2026-04-21 13:47:45.019472     N/A                     GDECODIGO
13  2026-04-21 13:47:45.021561     N/A                          EAPB
14  2026-04-21 13:47:45.023497     N/A               BARRIO_O_VEREDA
15  2026-04-21 13:47:45.024758     N/A                     DIRECCION
16  2026-04-21 13:47:45.025901     N/A                      COD_PAIS
17  2026-04-21 13:47:45.027010     N/A                          PAIS
18  2026-04-21 13:47:45.028155     N/A              FECHA_NACIMIENTO
19  2026-04-21 13:47:45.029264     N/A                    ADNINGRESO

       valor_original valor_nuevo  \
0   columna existente   ELIMINADO
1   columna existente   ELIMINADO
2   columna existente   ELIMINADO
3   columna existente   ELIMINADO
4   columna existente   ELIMINADO
5   columna existente   ELIMINADO
6   columna existente   ELIMINADO
7   columna existente   ELIMINADO
8   columna existente   ELIMINADO
9   columna existente   ELIMINADO
10  columna existente   ELIMINADO
11  columna existente   ELIMINADO
12  columna existente   ELIMINADO
13  columna existente   ELIMINADO
14  columna existente   ELIMINADO
15  columna existente   ELIMINADO
16  columna existente   ELIMINADO
17  columna existente   ELIMINADO
18  columna existente   ELIMINADO
19  columna existente   ELIMINADO

                                       regla_aplicada       accion  \
0   Exclusión por no aportar al análisis epidemiol...  Eliminación
1   Exclusión por no aportar al análisis epidemiol...  Eliminación
2   Exclusión por no aportar al análisis epidemiol...  Eliminación
3   Exclusión por no aportar al análisis epidemiol...  Eliminación
4   Exclusión por no aportar al análisis epidemiol...  Eliminación
5   Exclusión por no aportar al análisis epidemiol...  Eliminación
6   Exclusión por no aportar al análisis epidemiol...  Eliminación
7   Exclusión por no aportar al análisis epidemiol...  Eliminación
8   Exclusión por no aportar al análisis epidemiol...  Eliminación
9   Exclusión por no aportar al análisis epidemiol...  Eliminación
10  Exclusión por no aportar al análisis epidemiol...  Eliminación
11  Exclusión por no aportar al análisis epidemiol...  Eliminación
12  Exclusión por no aportar al análisis epidemiol...  Eliminación
13  Exclusión por no aportar al análisis epidemiol...  Eliminación
14  Exclusión por no aportar al análisis epidemiol...  Eliminación
15  Exclusión por no aportar al análisis epidemiol...  Eliminación
16  Exclusión por no aportar al análisis epidemiol...  Eliminación
17  Exclusión por no aportar al análisis epidemiol...  Eliminación
18  Exclusión por no aportar al análisis epidemiol...  Eliminación
19  Exclusión por no aportar al análisis epidemiol...  Eliminación

                      fase
0   Depuración de columnas
1   Depuración de columnas
2   Depuración de columnas
3   Depuración de columnas
4   Depuración de columnas
5   Depuración de columnas
6   Depuración de columnas
7   Depuración de columnas
8   Depuración de columnas
9   Depuración de columnas
10  Depuración de columnas
11  Depuración de columnas
12  Depuración de columnas
13  Depuración de columnas
14  Depuración de columnas
15  Depuración de columnas
16  Depuración de columnas
17  Depuración de columnas
18  Depuración de columnas
19  Depuración de columnas

In [26]:
df_limpio.head()

,CODIGO_FOLIO,GENERO,REGIMEN,TIPO_PACIENTE,MUNICIPIO,ZONA,FECHA_INGRESO,MES,AÑO,EDAD,NIVEL_SOCIOECONOMICO,ETNIA,CODIGO_INGRESO,TIPO_DIAGNOSTICO,CIE10,NOMBRE_DIAGNOSTICO,OCUPACION_PACIENTE
0,HC067W,Femenino,SUBSIDIADO,Subsidiado,EL CARMEN DE BOLÍVAR,Urbana,2024-12-30 19:06:39,diciembre,2024,82,NIVEL UNO,Ninguna,2032902,SECUNDARIO,I209,"ANGINA DE PECHO, NO ESPECIFICADA",TERCERA EDAD
1,HC067W,Femenino,SUBSIDIADO,Subsidiado,EL CARMEN DE BOLÍVAR,Urbana,2024-12-30 19:06:39,diciembre,2024,82,NIVEL UNO,Ninguna,2032902,PRINCIPAL,I509,"INSUFICIENCIA CARDIACA, NO ESPECIFICADA",TERCERA EDAD
2,HC093W,Femenino,SUBSIDIADO,Subsidiado,BOLÍVAR,Rural,2024-12-28 18:23:29,diciembre,2024,81,NIVEL UNO,Ninguna,2032378,SECUNDARIO,E660,OBESIDAD DEBIDA A EXCESO DE CALORIAS,TERCERA EDAD
3,HC093W,Femenino,SUBSIDIADO,Subsidiado,BOLÍVAR,Rural,2024-12-28 18:23:29,diciembre,2024,81,NIVEL UNO,Ninguna,2032378,SECUNDARIO,J189,"NEUMONIA, NO ESPECIFICADA",TERCERA EDAD
4,HC093W,Femenino,SUBSIDIADO,Subsidiado,BOLÍVAR,Rural,2024-12-28 18:23:29,diciembre,2024,81,NIVEL UNO,Ninguna,2032378,PRINCIPAL,J960,INSUFICIENCIA RESPIRATORIA AGUDA,TERCERA EDAD

## Excluir Folios

In [27]:
df_limpio, log = exfol.exluir_folios(df_limpio,log)

In [28]:
filas, columnas = df_limpio.shape
print(f"\nEl DataFrame depurado tiene {filas} filas y {columnas} columnas.")

El DataFrame depurado tiene 198072 filas y 17 columnas.

In [29]:
print(log.obtener().head(20))
log.exportar("data/output/trazabilidad.csv")

                     timestamp ingreso                         campo  \
0   2026-04-21 13:47:45.002081     N/A                           OID
1   2026-04-21 13:47:45.005938     N/A                     HCNTIPHIS
2   2026-04-21 13:47:45.007844     N/A                      HCNOMBRE
3   2026-04-21 13:47:45.009167     N/A                     NUM_FOLIO
4   2026-04-21 13:47:45.010337     N/A                   FECHA_FOLIO
5   2026-04-21 13:47:45.011530     N/A  MES_VERIFICADO_X_FECHA_FOLIO
6   2026-04-21 13:47:45.012672     N/A  AÑO_VERIFICADO_X_FECHA_FOLIO
7   2026-04-21 13:47:45.013818     N/A                     GENPACIEN
8   2026-04-21 13:47:45.014952     N/A           TIPO_IDENTIFICACION
9   2026-04-21 13:47:45.016088     N/A             HC_IDENTIFICACION
10  2026-04-21 13:47:45.017199     N/A               NOMBRE_PACIENTE
11  2026-04-21 13:47:45.018315     N/A                 GRADO_ESTUDIO
12  2026-04-21 13:47:45.019472     N/A                     GDECODIGO
13  2026-04-21 13:47:45.021561     N/A                          EAPB
14  2026-04-21 13:47:45.023497     N/A               BARRIO_O_VEREDA
15  2026-04-21 13:47:45.024758     N/A                     DIRECCION
16  2026-04-21 13:47:45.025901     N/A                      COD_PAIS
17  2026-04-21 13:47:45.027010     N/A                          PAIS
18  2026-04-21 13:47:45.028155     N/A              FECHA_NACIMIENTO
19  2026-04-21 13:47:45.029264     N/A                    ADNINGRESO

       valor_original valor_nuevo  \
0   columna existente   ELIMINADO
1   columna existente   ELIMINADO
2   columna existente   ELIMINADO
3   columna existente   ELIMINADO
4   columna existente   ELIMINADO
5   columna existente   ELIMINADO
6   columna existente   ELIMINADO
7   columna existente   ELIMINADO
8   columna existente   ELIMINADO
9   columna existente   ELIMINADO
10  columna existente   ELIMINADO
11  columna existente   ELIMINADO
12  columna existente   ELIMINADO
13  columna existente   ELIMINADO
14  columna existente   ELIMINADO
15  columna existente   ELIMINADO
16  columna existente   ELIMINADO
17  columna existente   ELIMINADO
18  columna existente   ELIMINADO
19  columna existente   ELIMINADO

                                       regla_aplicada       accion  \
0   Exclusión por no aportar al análisis epidemiol...  Eliminación
1   Exclusión por no aportar al análisis epidemiol...  Eliminación
2   Exclusión por no aportar al análisis epidemiol...  Eliminación
3   Exclusión por no aportar al análisis epidemiol...  Eliminación
4   Exclusión por no aportar al análisis epidemiol...  Eliminación
5   Exclusión por no aportar al análisis epidemiol...  Eliminación
6   Exclusión por no aportar al análisis epidemiol...  Eliminación
7   Exclusión por no aportar al análisis epidemiol...  Eliminación
8   Exclusión por no aportar al análisis epidemiol...  Eliminación
9   Exclusión por no aportar al análisis epidemiol...  Eliminación
10  Exclusión por no aportar al análisis epidemiol...  Eliminación
11  Exclusión por no aportar al análisis epidemiol...  Eliminación
12  Exclusión por no aportar al análisis epidemiol...  Eliminación
13  Exclusión por no aportar al análisis epidemiol...  Eliminación
14  Exclusión por no aportar al análisis epidemiol...  Eliminación
15  Exclusión por no aportar al análisis epidemiol...  Eliminación
16  Exclusión por no aportar al análisis epidemiol...  Eliminación
17  Exclusión por no aportar al análisis epidemiol...  Eliminación
18  Exclusión por no aportar al análisis epidemiol...  Eliminación
19  Exclusión por no aportar al análisis epidemiol...  Eliminación

                      fase
0   Depuración de columnas
1   Depuración de columnas
2   Depuración de columnas
3   Depuración de columnas
4   Depuración de columnas
5   Depuración de columnas
6   Depuración de columnas
7   Depuración de columnas
8   Depuración de columnas
9   Depuración de columnas
10  Depuración de columnas
11  Depuración de columnas
12  Depuración de columnas
13  Depuración de columnas
14  Depuración de columnas
15  Depuración de columnas
16  Depuración de columnas
17  Depuración de columnas
18  Depuración de columnas
19  Depuración de columnas
Log exportado en: data/output/trazabilidad.csv
Total de registros en log: 118

## Formatear Fechas

In [30]:
df_limpio, log = formcol.formatear_fechas(df_limpio,log)

log.exportar("data/output/trazabilidad.csv")

Log exportado en: data/output/trazabilidad.csv
Total de registros en log: 119

## Formatear Edad

In [31]:
df_limpio, log = formcol.formatear_edad(df_limpio, log) 
log.exportar("data/output/trazabilidad.csv")

Log exportado en: data/output/trazabilidad.csv
Total de registros en log: 120

## Eliminar Duplicados en Grupos A y B

In [32]:
df_grupo_a, log = grupo_a.depurar_grupo_a(df_limpio, log)
log.exportar("data/output/trazabilidad.csv")

[Fase 2 - Grupo A] Registros entrada: 8671 | Eliminados: 322 | Resultado: 8349
Log exportado en: data/output/trazabilidad.csv
Total de registros en log: 442

In [33]:
df_grupo_b, log = grupo_b.depurar_grupo_b(df_limpio, log)
log.exportar("data/output/trazabilidad.csv")

[Fase 2 - Grupo B] Registros entrada: 651 | Eliminados: 28 | Resultado: 623
Log exportado en: data/output/trazabilidad.csv
Total de registros en log: 470

## Unificar Folios

In [34]:
df_unificado, log = unificar_folios.unificar_folios(df_grupo_a, df_grupo_b, log)
log.exportar("data/output/trazabilidad.csv")

Log exportado en: data/output/trazabilidad.csv
Total de registros en log: 472